version: '3.8'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    # Зависимость от другого сервиса
    depends_on:
      - pgdb
      - minio

  pgdb:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=bookingclassrooms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: pgadmin
        PGADMIN_CONFIG_SERVER_MODE: 'False'
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
        - ./servers.json:/pgadmin4/servers.json
        - ./pgpass:/pgpass
      ports:
        - 127.0.0.1:5050:80
      restart: unless-stopped
  
  minio:
    image: minio/minio:RELEASE.2022-10-15T19-57-03Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: .env
    restart: always

volumes:
  pgdbdata: null
  pgadmin: