# Generated by Django 4.2.4 on 2024-10-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('moderator', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_event_time', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Действует'), (2, 'Удалена')], default=1, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'classrooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApplicationClassrooms',
            fields=[
                ('mm_id', models.AutoField(primary_key=True, serialize=False)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.applications')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.classrooms')),
            ],
            options={
                'db_table': 'application_classrooms',
                'managed': True,
            },
        ),
    ]
