# Generated by Django 4.2.4 on 2024-09-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationclassrooms',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='classrooms',
            options={'managed': False},
        ),
    ]
