# Generated by Django 4.2.4 on 2024-09-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_djangomigrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationClassrooms',
            fields=[
                ('mm_id', models.AutoField(primary_key=True, serialize=False)),
                ('finish_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_classrooms',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ApplicationClassroom',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
