# Generated by Django 4.2.4 on 2024-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_applications_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='event_date',
            field=models.DateTimeField(blank=True, default='2024-12-12 00:00', null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='start_event_time',
            field=models.TimeField(blank=True, default='12-00', null=True),
        ),
    ]
