# Generated by Django 4.2.4 on 2024-10-01 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applications_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='event_name',
            field=models.CharField(blank=True, default='конференция', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='start_event_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
    ]
