# Generated by Django 4.2.4 on 2024-09-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_applicationclassrooms_options_and_more'),
        ('app', '0003_applicationclassrooms_delete_applicationclassroom_and_more'),
    ]

    operations = [
    ]
