# Generated by Django 4.2.4 on 2024-09-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20240930_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationclassrooms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='classrooms',
            options={'managed': True},
        ),
    ]
