# Generated by Django 4.2.4 on 2024-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_applicationclassrooms_finish_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicationclassrooms',
            constraint=models.UniqueConstraint(fields=('classroom', 'app'), name='unique_ApplicationClassrooms'),
        ),
    ]
