# Generated by Django 4.2.4 on 2024-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applicationclassrooms_unique_applicationclassrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=100),
        ),
    ]
