# Generated by Django 4.2.4 on 2024-10-11 21:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_applications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 21, 58, 10, 986561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
