# Generated by Django 4.2.4 on 2024-10-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_applications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
