# Generated by Django 4.2.4 on 2024-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_applications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, null=True),
        ),
    ]
